### ISSUE TITLE
Провести проверку на большом файле

### ISSUE THREAD

**Issue by alexkoss** [ADsty/PeacockTeamInterview#1]
Добрый день! Меня зовут Александр, сотрудник компании БалтИнфоКом.

Предлагаю осуществить проверку на большом файле.

Файл: https://github.com/PeacockTeam/new-job/releases/download/v1.0/lng-big.7z

В ответе должно быть количество групп и время выполнения.

**Comment by ADsty** [comment]
Здравствуйте, Александр. 
Ответ на поставленную задачу: количество групп 105036, время выполнения при первом запуске вместе с записью в файл ровно 30 секунд.
К сожалению во время прогона файла обнаружилась парочка ботлнеков, которые не были выявлены на прошлых тестах, поэтому пришлось модернизировать программу и подстроиться под изменившиеся условия касательно пустых значений в строках (они читаются сканером без ""). Получилось слегка грязно поскольку я торопился, надеюсь Вы не против того что я внес изменения в программу. Сам файл с результатом представлен в проекте под названием result-big.txt.

**Comment by alexkoss** [comment]
Ответ корректный. Предлагаю сделать рефакторинг, возможно повысить скорость. Как зальёте, посмотрим код.
